FROM node:14.17.3-alpine
# RUN mkdir -p /usr/src/app
# WORKDIR /usr/src/app
# RUN npm install create-next-app
# RUN npm install -g typescript @types/react @types/node @types/react-redux
# RUN npm install -g redux react-redux axios redux-thunk @reduxjs/toolkit redux-persist react-redux
# RUN npm install --save-dev jest jest-dom @types/jest ts-jest @testing-library/dom @testing-library/jest-dom @testing-library/react babel-jest identity-obj-proxy react-test-renderer
# COPY . /usr/src/app/

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . /usr/src/app/
# RUN npm install